# Generated by Django 4.2.8 on 2023-12-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='thumbnail_url',
        ),
    ]
